"""JIG scaffold templates for `jigy init`."""

from jig.templates.templates import (
    BRICKS_YAML_TEMPLATE,
    CHARTER_MD_TEMPLATE,
    CONTEXT_JIG_MD_TEMPLATE,
    DO_PLAN_INSTRUCTIONS_TEMPLATE,
    DO_PLAN_SKILL_MD_TEMPLATE,
    DO_WU_TEMPLATE,
    JIG_CONTEXT_SKILL_MD_TEMPLATE,
    JIG_TOML_TEMPLATE,
    JIGPLAN_INSTRUCTIONS_TEMPLATE,
    JIGPLAN_SKILL_MD_TEMPLATE,
    PLAN_INSTRUCTIONS_TEMPLATE,
    PLAN_SKILL_MD_TEMPLATE,
    SKILL_MD_TEMPLATE,
)

__all__ = [
    "BRICKS_YAML_TEMPLATE",
    "CHARTER_MD_TEMPLATE",
    "CONTEXT_JIG_MD_TEMPLATE",
    "DO_PLAN_INSTRUCTIONS_TEMPLATE",
    "DO_PLAN_SKILL_MD_TEMPLATE",
    "DO_WU_TEMPLATE",
    "JIG_CONTEXT_SKILL_MD_TEMPLATE",
    "JIG_TOML_TEMPLATE",
    "JIGPLAN_INSTRUCTIONS_TEMPLATE",
    "JIGPLAN_SKILL_MD_TEMPLATE",
    "PLAN_INSTRUCTIONS_TEMPLATE",
    "PLAN_SKILL_MD_TEMPLATE",
    "SKILL_MD_TEMPLATE",
]
